### ISSUE TITLE
Test of ex_cldr v2.24.0-rc

### ISSUE THREAD

**Issue by kipcole9** [LostKobrakai/cldr_languages#9]
@LostKobrakai would you consider testing on [ex_cldr version 2.24.0-rc.3](https://hex.pm/packages/ex_cldr/2.24.0-rc.3)?  Its based upon [CLDR 40](https://cldr.unicode.org/index/downloads/cldr-40) due for release by the end of October but the data appears stable now.

There shouldn't be any changes that negative affect your package but would be great if you wouldn't mind checking?

**Comment by LostKobrakai** [comment]
I have a warning about `Cldr.Config.get_locale` https://github.com/elixir-cldr/cldr/commit/aeebf54ea6758a653deabaf4806f17a90cdda77f, but other than that tests pass. I want to keep compatibilty for older cldr versions so I wont update this one yet.

**Comment by kipcole9** [comment]
Understood Benjamin, glad it works (apart from the deprecation).  The idea is that I've made `Cldr.Locale.Loader` a public module and moved `get_locale/2` into it. This makes it public and supported which will make things somewhat clearer to anyone interested in access the data in its serialized form.

Since `Cldr.Config` isn't a public module I suppose I can remove the deprecation warning. But I also don't want to surprise anyone when I remove it at some time.

**Comment by LostKobrakai** [comment]
@kipcole9 I've reconsidered the position on not doing an update, however there's also `Cldr.Config.known_locale_names(config)` in most ex_cldr client libraries. I feel that one should be covered then as well.

**Comment by kipcole9** [comment]
Good suggestion @LostKobrakai, I am doing the same deprecation/move for `known_locale_names/1` and `known_rbnf_locale_names/1`.  I will have all my libs updated in the next hour.

**Comment by kipcole9** [comment]
I have updated `ex_cldr`, `ex_cldr_currencies`, `ex_cldr_numbers`, `ex_cldr_calendars`, `ex_cldr_lists`, `ex_cldr_units` and `ex_cldr_dates_times` to reflect the now-deprecated `Cldr.Config.known_locale_names/1`. It is replaced with `Cldr.Locale.Loader.known_locale_names/1`.

I'm not expecting any further changes prior to release on October 27th (subject to last minute issues of course).

**Comment by LostKobrakai** [comment]
Sounds good. I'll amend the PR and release the changes as rc this evening.

**Comment by kipcole9** [comment]
I have published [ex_cldr version 2.24.0](https://hex.pm/packages/ex_cldr/2.24.0) so hopefully your testing on the final release will allow you to publish a final release too.
